name: Update ranking list

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes

jobs:
  update-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Soft reset last commit
        run: |
          git reset --soft HEAD~1

      - name: Fetch latest ranking
        env:
          GITHUB_TOKEN: ${{ secrets.RUSTLINGS_GITHUB_TOKEN }}
          # The secret is a typo, but i don't want to change it
          RUSTLINGS_ASSIGNMENT_ID: ${{ secrets.RUSTINGS_ASSIGNMENT_ID }}
        run: |
          chmod +x LoongsonNeuq.RustlingsRank
          ./LoongsonNeuq.RustlingsRank

      - name: Set git committer
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update Rustlings ranking table"

      - name: Force push changes
        run: |
          git push origin main --force
